import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Carnival</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>The Carnival</h1>
        <Image
          className={styles.img}
          src="/coder.jpg"
          width={624}
          height={416}
          alt=""
        />
        <p className={styles.description}>
          Conversation is king. Content is just something to talk about
        </p>
        <h2>Latest Blogs</h2>
        <div className={styles.blog_home}>
          <h3>How to use the React component ?</h3>
          <p>Follow for more associative thing you need</p>
        </div>
        <h2>Popular Blogs</h2>
        <div className={styles.blog_home}>
          <h3>How to use the React component ?</h3>
          <p>Follow for more associative thing you need</p>
        </div>
      </main>
      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image
            className={styles.logo1}
            src="/logo.png"
            width={80}
            height={45}
          />
        </span>
      </footer>
    </div>
  );
}
